export const THEME_LIGHT = {
  bg: "bg-slate-50",
  card: "bg-white",
  cardHover: "hover:bg-slate-50",
  accent: "text-teal-600",
  accentBg: "bg-teal-500",
  accentHover: "hover:bg-teal-600",
  success: "text-emerald-500",
  error: "text-rose-500",
  border: "border-slate-200",
  text: "text-slate-800",
  textSecondary: "text-slate-500",
  textMuted: "text-slate-400",
  shadow: "shadow-sm",
  shadowHover: "hover:shadow-md",
  input: "bg-white border-slate-200",
  inputFocus: "focus:border-teal-500",
  header: "bg-white/80 border-slate-200",
  modal: "bg-white",
  modalOverlay: "bg-black/50",
};

export const THEME_DARK = {
  bg: "bg-slate-950",
  card: "bg-slate-900",
  cardHover: "hover:bg-slate-800",
  accent: "text-teal-400",
  accentBg: "bg-teal-500",
  accentHover: "hover:bg-teal-400",
  success: "text-emerald-400",
  error: "text-rose-400",
  border: "border-slate-800",
  text: "text-slate-100",
  textSecondary: "text-slate-400",
  textMuted: "text-slate-500",
  shadow: "shadow-lg shadow-black/20",
  shadowHover: "hover:shadow-xl",
  input: "bg-slate-800 border-slate-700",
  inputFocus: "focus:border-teal-500",
  header: "bg-slate-900/80 border-slate-800",
  modal: "bg-slate-900",
  modalOverlay: "bg-black/80",
};

export const getTheme = (isDark) => (isDark ? THEME_DARK : THEME_LIGHT);
